services:
  - type: web
    name: line-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: GEMINI_MODEL_NAME
        value: gemini-2.0-flash
      - key: GEMINI_TEMPERATURE
        value: 0.9
      - key: GEMINI_TOP_P
        value: 0.8
      - key: GEMINI_TOP_K
        value: 40
